name: Fix Format

on:
  issue_comment:
    types: [created]
  workflow_call:

jobs:
  fix-format:
    name: Fix format
    if: github.event_name == 'issue_comment' && github.event.comment.body == '/fix-format'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: read
    outputs:
      pull_request_number: ${{ steps.pr-data.outputs.pull_request_number }}
      source_branch: ${{ steps.pr-data.outputs.source_branch }}

    steps:
      - name: Get PR Source Branch
        uses: actions/github-script@v7
        id: pr-data
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;

            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            core.setOutput('pull_request_number', prNumber);
            core.setOutput('source_branch', pr.data.head.ref);

            return {
              source_branch: pr.data.head.ref,
              base_branch: pr.data.base.ref
            };

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJSON(steps.pr-data.outputs.result).source_branch }}

      # Prettier must be in `package.json`
      - name: Install Node.js dependencies
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci

      - name: Fix formatting
        run: npm run format:fix

      - name: Add & Commit
        id: commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: Automated format
          push: true

  rerun-checks:
    needs: fix-format
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.fix-format.outputs.source_branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install @octokit/rest node-fetch

      - name: Rerun checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ needs.fix-format.outputs.pull_request_number }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: node ./.github/actions/rerun-checks.js
